site_name: Marsworks
site_description: Documentation for Marsworks. An API Wrapper for NASA's Mars Rover Photos API written in Python.
site_author: NovaEmiya
site_url: https://novaemiya.github.io/Marsworks/

theme:
  features:
    - navigation.top
  name: material
  logo: img/rover.png
  favicon: img/rover.ico
  palette:
    - scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - Changelog: changelog.md
  - API-Reference:
    - Client: API-Reference/client.md
    - Manifest: API-Reference/manifest.md
    - Photo: API-Reference/photo.md
    - Exceptions: API-Reference/exceptions.md
    - Helpers: API-Reference/helpers.md
    - Enums:
      - Rover: API-Reference/Enums/rover.md
      - Camera: API-Reference/Enums/camera.md

plugins:
- search
- mkdocstrings

repo_name: NovaEmiya/Marsworks
repo_url: https://github.com/NovaEmiya/Marsworks

extra_css:
- ./css/margin.css
copyright: Copyright 2021 - Present &copy; NovaEmiya

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: "+"
